name: "publish haddock"
on:
  push:
    branches:
      - master
jobs:
  bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes ca-derivations
          extra-substituters = https://cache.iog.io
          extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - name: Build Haddock
      run: |
        mkdir out        
        nix develop --command cabal haddock --builddir=./out | tee >(tail -1 | xargs -L 1 dirname > haddock_path)
        echo "HADDOCK_PATH=$(cat haddock_path)" >> $GITHUB_ENV

    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: ${{ env.HADDOCK_PATH }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4        

