name: "publish haddock"
on:
  push:
    branches:
      - master
jobs:
  bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes ca-derivations
          extra-substituters = https://cache.iog.io
          extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - name: Build Haddock
      run: nix develop --command cabal haddock

          
